### ISSUE TITLE
Find a good Kanban or Scrum board

### ISSUE THREAD

**Issue by daweim0** [RockRaidersInc/ROS-Main#10]
Leads - https://medium.com/@rohamg/beyond-code-using-github-for-every-company-workflow-1d973f00c5db
https://www.quora.com/What-are-some-Kanban-Tools-with-Git-Integration
https://www.atlassian.com/agile/kanban/kanban-vs-scrum

**Comment by sigi73** [comment]
The teams here use jira. 

https://www.atlassian.com/software/jira
Theres also github integration https://confluence.atlassian.com/adminjiracloud/connect-jira-cloud-to-github-814188429.html
