### ISSUE TITLE
Select cameras

### ISSUE THREAD

**Issue by cmcgowan27** [RockRaidersInc/ROS-Main#19]

**Comment by daweim0** [comment]
Is there anything wrong with the IP cameras we already have? Maybe latency was a problem?

**Comment by daweim0** [comment]
This webcam looks good enough and pretty cheap (and it's from a reputable manufacturer). We should use a high res camera (like the zed) for tennis ball detection, but this should be good enough for the rest of our cameras. https://www.newegg.com/logitech-960-000694-c270/p/N82E16826104648
