### ISSUE TITLE
Similar code in logitech_controller and drive packages

### ISSUE THREAD

**Issue by nfusionz** [RockRaidersInc/ROS-Main#6]
There are two different files in the repo that are based off of the same code:
+ [https://github.com/RockRaidersInc/ROS-Main/blob/master/logitech_controller/src/joystick_read.py](url)
+ [https://github.com/RockRaidersInc/ROS-Main/blob/master/drive/src/joystick_read.py](url)

The code in the drive package seems to be more recent, but which one needs to be kept?

**Comment by daweim0** [comment]
I'd also guess the drive package version. Not only does it do the exact same thing but with a little more error checking, it also has a lot more supporting code around it.
